/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DealersAndVehicles) {
      root.DealersAndVehicles = {};
    }
    root.DealersAndVehicles.AnswerResponse = factory(root.DealersAndVehicles.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AnswerResponse model module.
   * @module model/AnswerResponse
   * @version v1
   */

  /**
   * Constructs a new <code>AnswerResponse</code>.
   * @alias module:model/AnswerResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AnswerResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnswerResponse} obj Optional instance to populate.
   * @return {module:model/AnswerResponse} The populated <code>AnswerResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('totalMilliseconds'))
        obj.totalMilliseconds = ApiClient.convertToType(data['totalMilliseconds'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Boolean} success
   */
  exports.prototype.success = undefined;

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {Number} totalMilliseconds
   */
  exports.prototype.totalMilliseconds = undefined;


  return exports;

}));
