/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DealersAndVehicles) {
      root.DealersAndVehicles = {};
    }
    root.DealersAndVehicles.DatasetIdResponse = factory(root.DealersAndVehicles.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DatasetIdResponse model module.
   * @module model/DatasetIdResponse
   * @version v1
   */

  /**
   * Constructs a new <code>DatasetIdResponse</code>.
   * @alias module:model/DatasetIdResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DatasetIdResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetIdResponse} obj Optional instance to populate.
   * @return {module:model/DatasetIdResponse} The populated <code>DatasetIdResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('datasetId'))
        obj.datasetId = ApiClient.convertToType(data['datasetId'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} datasetId
   */
  exports.prototype.datasetId = undefined;


  return exports;

}));
