/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DealersAndVehicles) {
      root.DealersAndVehicles = {};
    }
    root.DealersAndVehicles.VehicleResponse = factory(root.DealersAndVehicles.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The VehicleResponse model module.
   * @module model/VehicleResponse
   * @version v1
   */

  /**
   * Constructs a new <code>VehicleResponse</code>.
   * @alias module:model/VehicleResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>VehicleResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VehicleResponse} obj Optional instance to populate.
   * @return {module:model/VehicleResponse} The populated <code>VehicleResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('vehicleId'))
        obj.vehicleId = ApiClient.convertToType(data['vehicleId'], 'Number');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
      if (data.hasOwnProperty('make'))
        obj.make = ApiClient.convertToType(data['make'], 'String');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('dealerId'))
        obj.dealerId = ApiClient.convertToType(data['dealerId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} vehicleId
   */
  exports.prototype.vehicleId = undefined;

  /**
   * @member {Number} year
   */
  exports.prototype.year = undefined;

  /**
   * @member {String} make
   */
  exports.prototype.make = undefined;

  /**
   * @member {String} model
   */
  exports.prototype.model = undefined;

  /**
   * @member {Number} dealerId
   */
  exports.prototype.dealerId = undefined;


  return exports;

}));
