/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DealersResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DealersResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.DealersAndVehicles) {
      root.DealersAndVehicles = {};
    }
    root.DealersAndVehicles.DealersApi = factory(root.DealersAndVehicles.ApiClient, root.DealersAndVehicles.DealersResponse);
  }
}(this, function(ApiClient, DealersResponse) {
  'use strict';

  /**
   * Dealers service.
   * @module api/DealersApi
   * @version v1
   */

  /**
   * Constructs a new DealersApi. 
   * @alias module:api/DealersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getDealer operation.
     * @callback module:api/DealersApi~getDealerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DealersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get information about a dealer
     * @param {String} datasetId 
     * @param {Number} dealerid 
     * @param {module:api/DealersApi~getDealerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DealersResponse}
     */
    this.getDealer = function(datasetId, dealerid, callback) {
      var postBody = null;

      // verify the required parameter 'datasetId' is set
      if (datasetId === undefined || datasetId === null) {
        throw new Error("Missing the required parameter 'datasetId' when calling getDealer");
      }

      // verify the required parameter 'dealerid' is set
      if (dealerid === undefined || dealerid === null) {
        throw new Error("Missing the required parameter 'dealerid' when calling getDealer");
      }


      var pathParams = {
        'datasetId': datasetId,
        'dealerid': dealerid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = DealersResponse;

      return this.apiClient.callApi(
        '/api/{datasetId}/dealers/{dealerid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
