/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VehicleIdsResponse', 'model/VehicleResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/VehicleIdsResponse'), require('../model/VehicleResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.DealersAndVehicles) {
      root.DealersAndVehicles = {};
    }
    root.DealersAndVehicles.VehiclesApi = factory(root.DealersAndVehicles.ApiClient, root.DealersAndVehicles.VehicleIdsResponse, root.DealersAndVehicles.VehicleResponse);
  }
}(this, function(ApiClient, VehicleIdsResponse, VehicleResponse) {
  'use strict';

  /**
   * Vehicles service.
   * @module api/VehiclesApi
   * @version v1
   */

  /**
   * Constructs a new VehiclesApi. 
   * @alias module:api/VehiclesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getIds operation.
     * @callback module:api/VehiclesApi~getIdsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleIdsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all vehicleids in dataset
     * @param {String} datasetId 
     * @param {module:api/VehiclesApi~getIdsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleIdsResponse}
     */
    this.getIds = function(datasetId, callback) {
      var postBody = null;

      // verify the required parameter 'datasetId' is set
      if (datasetId === undefined || datasetId === null) {
        throw new Error("Missing the required parameter 'datasetId' when calling getIds");
      }


      var pathParams = {
        'datasetId': datasetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = VehicleIdsResponse;

      return this.apiClient.callApi(
        '/api/{datasetId}/vehicles', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehicle operation.
     * @callback module:api/VehiclesApi~getVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get information about a vehicle
     * @param {String} datasetId 
     * @param {Number} vehicleid 
     * @param {module:api/VehiclesApi~getVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleResponse}
     */
    this.getVehicle = function(datasetId, vehicleid, callback) {
      var postBody = null;

      // verify the required parameter 'datasetId' is set
      if (datasetId === undefined || datasetId === null) {
        throw new Error("Missing the required parameter 'datasetId' when calling getVehicle");
      }

      // verify the required parameter 'vehicleid' is set
      if (vehicleid === undefined || vehicleid === null) {
        throw new Error("Missing the required parameter 'vehicleid' when calling getVehicle");
      }


      var pathParams = {
        'datasetId': datasetId,
        'vehicleid': vehicleid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['text/plain', 'application/json', 'text/json'];
      var returnType = VehicleResponse;

      return this.apiClient.callApi(
        '/api/{datasetId}/vehicles/{vehicleid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
