/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DealersAndVehicles);
  }
}(this, function(expect, DealersAndVehicles) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DatasetIdResponse', function() {
      beforeEach(function() {
        instance = new DealersAndVehicles.DatasetIdResponse();
      });

      it('should create an instance of DatasetIdResponse', function(done) {

        expect(instance).to.be.a(DealersAndVehicles.DatasetIdResponse);
        done();
      });

      it('should have the property datasetId (base name: "datasetId")', function(done) {
        instance.datasetId = "22EgCqTL2Ag"
        
        expect(instance).to.have.property('datasetId');
        expect(instance.datasetId).to.be.a('string');
        done();
      });

    });
  });

}));
