/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DealersAndVehicles);
  }
}(this, function(expect, DealersAndVehicles) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VehicleResponse', function() {
      beforeEach(function() {
        instance = new DealersAndVehicles.VehicleResponse();
      });

      it('should create an instance of VehicleResponse', function(done) {
        
        expect(instance).to.be.a(DealersAndVehicles.VehicleResponse);
        done();
      });

      it('should have the property vehicleId (base name: "vehicleId")', function(done) {
        instance.vehicleId = 2029649430;

        expect(instance).to.have.property('vehicleId');
        expect(instance.vehicleId).to.be.a('number');
        done();
      });

      it('should have the property year (base name: "year")', function(done) {
        instance.year = 2016;

        expect(instance).to.have.property('year');
        expect(instance.year).to.be.a('number');
        done();
      });

      it('should have the property make (base name: "make")', function(done) {
        instance.make = "Honda";

        expect(instance).to.have.property('make');
        expect(instance.make).to.be.a('string');
        done();
      });

      it('should have the property model (base name: "model")', function(done) {
        instance.model = "Accord";

        expect(instance).to.have.property('model');
        expect(instance.model).to.be.a('string');
        done();
      });

      it('should have the property dealerId (base name: "dealerId")', function(done) {
        instance.dealerId = 1493533791;

        expect(instance).to.have.property('dealerId');
        expect(instance.dealerId).to.be.a('number');
        done();
      });

    });
  });

}));
