/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DealersAndVehicles);
  }
}(this, function (expect, DealersAndVehicles) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new DealersAndVehicles.ClientApi();
  });

  describe('(package)', function () {
    describe('ClientApi', function () {
      describe('generate', function () {
        it('should call generate successfully', function (done) {
          var language = "javascript";

          instance.generate(language, function (error, data, response) {

            if (error) {
              done(error);
              return;
            }
            expect(data).to.be.empty()
            expect(response).to.have.status(200)
            done();
          });
          done();
        });
      });
      describe('index', function () {
        it('should call index successfully', function (done) {

          instance.index(function (error, data, response) {

            if (error) {
              done(error);
              return;
            }
            expect(data).to.be.empty()
            expect(response).to.have.status(200)
            done();
          });
          done();
        });
      });
    });
  });
}));
